module.exports  = [
  "vizabi-reactive",
  "vizabi-shared-components",
  'vizabi-barrankchart',
  // 'vizabi',
  'vizabi-bubblechart',
  // 'vizabi-mountainchart',
  'vizabi-linechart',
  // 'vizabi-cartogram',
  // 'vizabi-popbyage',
  // 'vizabi-extapimap',
  'vizabi-bubblemap',
  // 'vizabi-barchart-ds',
  // 'vizabi-sankey',
  // 'vizabi-spreadsheet',
];